### ISSUE TITLE
Mistake building URIs in edit UI

### ISSUE THREAD

**Issue by dr-shorthair** [UKGovLD/registry-config-base#5]
Steps to reproduce:

1. Build a LDR instance with a baseURI that includes a path following the domain
    - in our case http://environment.data.gov.au/def 

2. login, open edit dialogue, make a change, select [Save changes] 
--- Save failed: Bad Request - Payload URI does not match target ---

Inspection of the request URL shows that an extra /def has been inserted in the URL. 
When this is removed, everything is fine. 

Looks like perhaps the algorithm for building the request URL has parsed some input to find the end of the domain, rather than the end of the baseURI ??

**Comment by dr-shorthair** [comment]
I'm reasonably sure the problem is line 37 in edit-form.vm

              #set($posturl = $editTarget.uRI.replaceAll("^https?://[^/]*/","/"))

This converts
            http://environment.data.gov.au/def/sandbox --> /def/sandbox 
which is grabbing too much of the target URL (given that the baseURI is http://environment.data.gov.au/def ).

**Comment by der** [comment]
I haven't had time to try replicating this but going by eyeballing code I'm not sure it's that simple.

The `$posturl` is where the PUT/POST ajax request will be sent. The point of stripping off the domain is to catch for development/test setups where we are serving the edit page from e.g. localhost. The value of $posturl is supposed to start with "/" and so be relative to the server root thus in your case `/def/sandbox` should be the right URL to post to. Yet you say there is an "extra" `/def`and I can't see where that is coming from.

Is this a deployed service running at http://environment.data.gov.au/def or is it a test service?

If it's a test service is the registry running as a root webapp or running with at context "/def"?  If the former then that's the problem.

**Comment by dr-shorthair** [comment]
Yes, I guess that is the problem. It is a test service - running at http://localhost:NNNNN, but with the baseURI set to http://environment.data.gov.au/def   So I guess the NGINX magic is getting tripped up. The tricks being used to 'cater for development/test setups' is not matching our needs. 

Are you suggesting that I should deploy the test at http://localhost:NNNNN/def instead? 
Not sure if we can do that with the container technology - I'll have to check with Ben. 
(The point of the container, of course, is to pre-build, test and load a running service that can just be dropped onto a server when ready.)

**Comment by der** [comment]
Nothing to do with nginx, that's a completely separate issue.

Yes, if you are declaring the base URI to be http://host/def then I would expect the LDR instance to be running at /def both in production and testing. That should be trivial - call your war instance def.war and load that instead of ROOT.war.

If you want to run at http://localhost/ in both production and testing and use either Apache or nginx to map the URIs then you can do that and the edit code will work but you need both production and testing to be the same set up, including the front end rewrites.

If you want to run a different configuration in test from production then that's obviously harder. You could do it by comparing the URI prefix to the configured base URI and if they don't match assume you are in a test set up and create a different posturl. However, the risk then is that your set up might pass in testing but not work in production due a bug in that test-detection code.

**Comment by dr-shorthair** [comment]
Well that was easy. Tried your first suggestion and all OK now.

**Comment by der** [comment]
Glad it's sorted
